package user

trait ComponentRegistry
extends UserServiceComponent
with UserRepositoryComponent

object ComponentRegistryImpl
extends ComponentRegistry
with UserServiceComponentImpl
with UserRepositoryComponentImpl
